image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Conda Environment
    init: >
      echo "Creating Conda Environment..." &&
      conda env create -f environment.yml &&
      echo "Activating Conda Environment..." &&
      echo "conda activate variant_calling" >> ~/.bashrc

ports:
  - port: 8888
    onOpen: open-preview
